### ISSUE TITLE
For database I recommend you choose MongoDB

### ISSUE THREAD

**Issue by nodkz** [cdebotton/react-universal#6]
Take popular MongoDB ODM:
https://github.com/Automattic/mongoose

And wrap it with a mongoose schema converter to graphql:
https://github.com/RisingStack/graffiti-mongoose

**Comment by cdebotton** [comment]
Thank you for the suggestion, but I'm either going to not include a data layer explicitly in this repository (just the GraphQL setup, you can add whatever data layer you'd like in the resolve hooks), or I may implement graphql-sequelze when mickhansen/graphql-sequelize#38 is sorted out.

**Comment by cdebotton** [comment]
Thank you for the suggestion, but I'm either going to not include a data layer explicitly in this repository (just the GraphQL setup, you can add whatever data layer you'd like in the resolve hooks), or I may implement graphql-sequelize when mickhansen/graphql-sequelize#38 is sorted out.
